resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    server_name _;

    # Front Barber - /front-barber/
    location /front-barber/ {
        set $front http://front-barber;
        rewrite ^/front-barber/(.*) /$1 break;
        proxy_pass $front;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Security - /security/api e /security/api-docs
    location /security/ {
        set $security http://security:3001;
        rewrite ^/security/(.*) /$1 break;
        proxy_pass $security;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # BFF Negócios - /bff-negocios/api e /bff-negocios/api-docs
    location /bff-negocios/ {
        set $bff http://bff-negocios:3002;
        rewrite ^/bff-negocios/(.*) /$1 break;
        proxy_pass $bff;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
