resolver 127.0.0.11 valid=10s;

server {
    listen 80;
    server_name _;

    # Security
    location /api {
        set $security http://security:3001;
        proxy_pass $security;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api-docs {
        set $security http://security:3001;
        proxy_pass $security;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # BFF Negócios
    location /api/negocios {
        set $bff http://bff-negocios:3002;
        proxy_pass $bff;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /bff-docs {
        set $bff http://bff-negocios:3002;
        proxy_pass $bff/api-docs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
